In [1]:
# Start by importing necessary packages
import requests
import pandas as pd
import numpy as np
from IPython.display import display
from io import StringIO

from dstapi import DstApi # The helper class

In [2]:
# Directly embed parameters in the URL with response.get()
requests.get('https://api.statbank.dk/v1' + '/tableinfo' + "?id=metrox1&format=JSON").json()

# Pass a dictionary of parameters to requests.get()
params = {'id': 'NAIO3', 'format': 'JSON'}
requests.get('https://api.statbank.dk/v1' + '/tableinfo', params=params).json()

# Use response.post() - note the change in the name of the parameter about the table's name
# I'm also adding here a language parameter - most tables are available in both Danish and English
params = {'table': 'NAIO5', 'format': 'JSON', 'lang':'da'}
requests.post('https://api.statbank.dk/v1' + '/tableinfo', json=params).json()

{'id': 'NAIO5',
 'text': 'Beskæftigelse og timer',
 'description': 'Beskæftigelse og timer efter socioøkonomisk status, branche og tid',
 'unit': '-',
 'suppressedDataValue': '0',
 'updated': '2025-06-30T08:00:00',
 'active': True,
 'contacts': [{'name': 'Peter Rørmose Jensen',
   'phone': '+4540135126',
   'mail': 'prj@dst.dk'}],
 'documentation': {'id': 'add44c1a-760f-4b22-9aea-82cf93b4da68',
  'url': 'https://www.dst.dk/statistikdokumentation/add44c1a-760f-4b22-9aea-82cf93b4da68'},
 'footnote': None,
 'variables': [{'id': 'SOCIO',
   'text': 'socioøkonomisk status',
   'elimination': False,
   'time': False,
   'values': [{'id': 'EMPH_DC',
     'text': 'Samlede præsterede timer (1000 timer)'},
    {'id': 'SALH_DC',
     'text': 'Præsterede timer for lønmodtagere (1000 timer)'},
    {'id': 'SELFH_DC',
     'text': 'Præsterede timer for selvstændige (1000 timer)'},
    {'id': 'EMPM_DC', 'text': 'Samlet antal beskæftigede (antal)'},
    {'id': 'SALM_DC', 'text': 'Lønmodtagere (antal)'},
    {'id': 'SELFM_DC', 'text': 'Selvstændige (antal)'},
    {'id': 'EMPEM_DC',
     'text': 'Samlet antal beskæftigede ekskl. orlov mv. (antal)'},
    {'id': 'SALEM_DC', 'text': 'Lønmodtagere ekskl. orlov mv. (antal)'},
    {'id': 'SELFEM_DC', 'text': 'Selvstændige ekskl. orlov mv. (antal)'}]},
  {'id': 'BRANCHE',
   'text': 'branche',
   'elimination': True,
   'time': False,
   'values': [{'id': 'V', 'text': 'I alt'},
    {'id': 'VA', 'text': 'A Landbrug, skovbrug og fiskeri'},
    {'id': 'V01000', 'text': '01000 Landbrug og gartneri'},
    {'id': 'V010000', 'text': '010000 Landbrug og gartneri'},
    {'id': 'V02000', 'text': '02000 Skovbrug'},
    {'id': 'V020000', 'text': '020000 Skovbrug'},
    {'id': 'V03000', 'text': '03000 Fiskeri'},
    {'id': 'V030000', 'text': '030000 Fiskeri'},
    {'id': 'VB', 'text': 'B Råstofindvinding'},
    {'id': 'V06090', 'text': '06090 Råstofindvinding'},
    {'id': 'V060000', 'text': '060000 Indvinding af olie og gas'},
    {'id': 'V080090', 'text': '080090 Indvinding af grus og sten'},
    {'id': 'V090000', 'text': '090000 Service til råstofindvinding'},
    {'id': 'VC', 'text': 'C Industri'},
    {'id': 'VCA', 'text': 'CA Føde-, drikke- og tobaksvareindustri'},
    {'id': 'V10120', 'text': '10120 Føde-, drikke- og tobaksvareindustri'},
    {'id': 'V100010', 'text': '100010 Slagterier'},
    {'id': 'V100020', 'text': '100020 Fiskeindustri'},
    {'id': 'V100030', 'text': '100030 Mejerier'},
    {'id': 'V100040', 'text': '100040 Bagerier, brødfabrikker mv.'},
    {'id': 'V100050', 'text': '100050 Anden fødevareindustri'},
    {'id': 'V110000', 'text': '110000 Drikkevareindustri'},
    {'id': 'V120000', 'text': '120000 Tobaksindustri'},
    {'id': 'VCB', 'text': 'CB Tekstil- og læderindustri'},
    {'id': 'V13150', 'text': '13150 Tekstil- og læderindustri'},
    {'id': 'V130000', 'text': '130000 Tekstilindustri'},
    {'id': 'V140000', 'text': '140000 Beklædningsindustri'},
    {'id': 'V150000', 'text': '150000 Læder- og fodtøjsindustri'},
    {'id': 'VCC', 'text': 'CC Træ- og papirindustri, trykkerier'},
    {'id': 'V16000', 'text': '16000 Træindustri'},
    {'id': 'V160000', 'text': '160000 Træindustri'},
    {'id': 'V17000', 'text': '17000 Papirindustri'},
    {'id': 'V170000', 'text': '170000 Papirindustri'},
    {'id': 'V18000', 'text': '18000 Trykkerier mv.'},
    {'id': 'V180000', 'text': '180000 Trykkerier mv.'},
    {'id': 'VCD', 'text': 'CD Olieraffinaderier mv.'},
    {'id': 'V19000', 'text': '19000 Olieraffinaderier mv.'},
    {'id': 'V190000', 'text': '190000 Olieraffinaderier mv.'},
    {'id': 'VCE', 'text': 'CE Kemisk industri'},
    {'id': 'V20000', 'text': '20000 Kemisk industri'},
    {'id': 'V200010', 'text': '200010 Fremst. af basiskemikalier'},
    {'id': 'V200020', 'text': '200020 Fremst. af maling og sæbe mv.'},
    {'id': 'VCF', 'text': 'CF Medicinalindustri'},
    {'id': 'V21000', 'text': '21000 Medicinalindustri'},
    {'id': 'V210000', 'text': '210000 Medicinalindustri'},
    {'id': 'VCG', 'text': 'CG Plast-, glas- og betonindustri'},
    {'id': 'V22000', 'text': '22000 Plast- og gummiindustri'},
    {'id': 'V220000', 'text': '220000 Plast- og gummiindustri'},
    {'id': 'V23000', 'text': '23000 Glas- og betonindustri'},
    {'id': 'V230010', 'text': '230010 Glasindustri og keramisk industri'},
    {'id': 'V230020', 'text': '230020 Betonindustri og teglværker'},
    {'id': 'VCH', 'text': 'CH Metalindustri'},
    {'id': 'V24000', 'text': '24000 Fremst. af metal'},
    {'id': 'V240000', 'text': '240000 Fremst. af metal'},
    {'id': 'V25000', 'text': '25000 Metalvareindustri'},
    {'id': 'V250000', 'text': '250000 Metalvareindustri'},
    {'id': 'VCI', 'text': 'CI Elektronikindustri'},
    {'id': 'V26000', 'text': '26000 Elektronikindustri'},
    {'id': 'V260010',
     'text': '260010 Fremst. af computere og kommunikationsudstyr mv.'},
    {'id': 'V260020', 'text': '260020 Fremst. af andet elektronisk udstyr'},
    {'id': 'VCJ', 'text': 'CJ Fremst. af elektrisk udstyr'},
    {'id': 'V27000', 'text': '27000 Fremst. af elektrisk udstyr'},
    {'id': 'V270010', 'text': '270010 Fremst. af elektriske motorer mv.'},
    {'id': 'V270020', 'text': '270020 Fremst. af ledninger og kabler'},
    {'id': 'V270030',
     'text': '270030 Fremst. af husholdningsapparater, lamper mv.'},
    {'id': 'VCK', 'text': 'CK Maskinindustri'},
    {'id': 'V28000', 'text': '28000 Maskinindustri'},
    {'id': 'V280010',
     'text': '280010 Fremst. af motorer, vindmøller og pumper'},
    {'id': 'V280020', 'text': '280020 Fremst. af andre maskiner'},
    {'id': 'VCL', 'text': 'CL Transportmiddelindustri'},
    {'id': 'V29000', 'text': '29000 Fremst. af motorkøretøjer og dele hertil'},
    {'id': 'V290000',
     'text': '290000 Fremst. af motorkøretøjer og dele hertil'},
    {'id': 'V30000',
     'text': '30000 Fremst. af skibe og andre transportmidler'},
    {'id': 'V300000',
     'text': '300000 Fremst. af skibe og andre transportmidler'},
    {'id': 'VCM', 'text': 'CM Møbel- og anden industri mv.'},
    {'id': 'V31320', 'text': '31320 Møbel- og anden industri'},
    {'id': 'V310000', 'text': '310000 Møbelindustri'},
    {'id': 'V320010', 'text': '320010 Fremst. af medicinske instrumenter mv.'},
    {'id': 'V320020',
     'text': '320020 Legetøj og anden fremstillingsvirksomhed'},
    {'id': 'V33000',
     'text': '33000 Reparation og installation af maskiner og udstyr'},
    {'id': 'V330000',
     'text': '330000 Reparation og installation af maskiner og udstyr'},
    {'id': 'VD_E', 'text': 'D_E Forsyningsvirksomhed'},
    {'id': 'VD', 'text': 'D Energiforsyning'},
    {'id': 'V35000', 'text': '35000 Energiforsyning'},
    {'id': 'V350010', 'text': '350010 Elforsyning'},
    {'id': 'V350020', 'text': '350020 Gasforsyning'},
    {'id': 'V350030', 'text': '350030 Varmeforsyning'},
    {'id': 'VE', 'text': 'E Vandforsyning og renovation'},
    {'id': 'V36000', 'text': '36000 Vandforsyning'},
    {'id': 'V360000', 'text': '360000 Vandforsyning'},
    {'id': 'V37390', 'text': '37390 Renovation, affaldsbehandling mv.'},
    {'id': 'V370000', 'text': '370000 Kloak- og rensningsanlæg'},
    {'id': 'V383900',
     'text': '383900 Renovation, genbrug og forureningsbekæmpelse'},
    {'id': 'VF', 'text': 'F Bygge og anlæg'},
    {'id': 'V41430', 'text': '41430 Bygge og anlæg'},
    {'id': 'V410009', 'text': '410009 Nybyggeri'},
    {'id': 'V420000', 'text': '420000 Anlægsvirksomhed'},
    {'id': 'V430003',
     'text': '430003 Professionel reparation og vedligeholdelse af bygninger'},
    {'id': 'V430004',
     'text': '430004 Gør-det-selv reparation og vedligeholdelse af boliger'},
    {'id': 'VG_I', 'text': 'G_I Handel og transport mv.'},
    {'id': 'VG', 'text': 'G Handel'},
    {'id': 'V45000', 'text': '45000 Bilhandel og -værksteder mv.'},
    {'id': 'V450010', 'text': '450010 Bilhandel'},
    {'id': 'V450020', 'text': '450020 Bilværksteder mv.'},
    {'id': 'V46000', 'text': '46000 Engroshandel'},
    {'id': 'V460000', 'text': '460000 Engroshandel'},
    {'id': 'V47000', 'text': '47000 Detailhandel'},
    {'id': 'V470000', 'text': '470000 Detailhandel'},
    {'id': 'VH', 'text': 'H Transport'},
    {'id': 'V49000', 'text': '49000 Landtransport'},
    {'id': 'V490010', 'text': '490010 Regional- og fjerntog'},
    {'id': 'V490020', 'text': '490020 Lokaltog, bus og taxi mv.'},
    {'id': 'V490030', 'text': '490030 Fragtvognmænd og rørtransport'},
    {'id': 'V50000', 'text': '50000 Skibsfart'},
    {'id': 'V500000', 'text': '500000 Skibsfart'},
    {'id': 'V51000', 'text': '51000 Luftfart'},
    {'id': 'V510000', 'text': '510000 Luftfart'},
    {'id': 'V52000', 'text': '52000 Hjælpevirksomhed til transport'},
    {'id': 'V520000', 'text': '520000 Hjælpevirksomhed til transport'},
    {'id': 'V53000', 'text': '53000 Post og kurertjeneste'},
    {'id': 'V530000', 'text': '530000 Post og kurertjeneste'},
    {'id': 'VI', 'text': 'I Hoteller og restauranter'},
    {'id': 'V55560', 'text': '55560 Hoteller og restauranter'},
    {'id': 'V550000', 'text': '550000 Hoteller mv.'},
    {'id': 'V560000', 'text': '560000 Restauranter'},
    {'id': 'VJ', 'text': 'J Information og kommunikation'},
    {'id': 'VJA', 'text': 'JA Forlag, tv og radio'},
    {'id': 'V58000', 'text': '58000 Udgivervirksomhed'},
    {'id': 'V580010', 'text': '580010 Forlag'},
    {'id': 'V580020',
     'text': '580020 Udgivelse af computerspil og anden software'},
    {'id': 'V59600',
     'text': '59600 Radio- og tv-stationer samt produktion af film, tv, mus'},
    {'id': 'V590000', 'text': '590000 Produktion af film, tv og musik mv.'},
    {'id': 'V600000', 'text': '600000 Radio- og tv-stationer'},
    {'id': 'VJB', 'text': 'JB Telekommunikation'},
    {'id': 'V61000', 'text': '61000 Telekommunikation'},
    {'id': 'V610000', 'text': '610000 Telekommunikation'},
    {'id': 'VJC', 'text': 'JC It- og informationstjenester'},
    {'id': 'V62630', 'text': '62630 It- og informationstjenester'},
    {'id': 'V620000', 'text': '620000 It-konsulenter mv.'},
    {'id': 'V630000', 'text': '630000 Informationstjenester'},
    {'id': 'VK', 'text': 'K Finansiering og forsikring'},
    {'id': 'V64000', 'text': '64000 Finansiel virksomhed'},
    {'id': 'V640010', 'text': '640010 Pengeinstitutter'},
    {'id': 'V640020', 'text': '640020 Kreditforeninger mv.'},
    {'id': 'V65000', 'text': '65000 Forsikring og pension'},
    {'id': 'V650000', 'text': '650000 Forsikring og pension'},
    {'id': 'V66000', 'text': '66000 Finansiel service'},
    {'id': 'V660000', 'text': '660000 Finansiel service'},
    {'id': 'VLA',
     'text': 'LA Ejendomshandel og udlejning af erhvervsejendomme'},
    {'id': 'V68100', 'text': '68100 Ejendomsmæglere mv.'},
    {'id': 'V680010', 'text': '680010 Ejendomsmæglere mv.'},
    {'id': 'V68300', 'text': '68300 Udlejning af erhvervsejendomme'},
    {'id': 'V680030', 'text': '680030 Udlejning af erhvervsejendomme'},
    {'id': 'VLB', 'text': 'LB Boliger'},
    {'id': 'V68203', 'text': '68203 Boliger, husleje i lejeboliger'},
    {'id': 'V680023', 'text': '680023 Boliger, husleje i lejeboliger'},
    {'id': 'V68204', 'text': '68204 Boliger, ejerboliger mv.'},
    {'id': 'V680024', 'text': '680024 Boliger, ejerboliger mv.'},
    {'id': 'VM_N', 'text': 'M_N Erhvervsservice'},
    {'id': 'VM', 'text': 'M Videnservice'},
    {'id': 'VMA', 'text': 'MA Rådgivning mv.'},
    {'id': 'V69700',
     'text': '69700 Advokater, revisorer og virksomhedskonsulenter'},
    {'id': 'V690010', 'text': '690010 Advokatvirksomhed'},
    {'id': 'V690020', 'text': '690020 Revision og bogføring'},
    {'id': 'V700000', 'text': '700000 Virksomhedskonsulenter'},
    {'id': 'V71000', 'text': '71000 Arkitekter og rådgivende ingeniører'},
    {'id': 'V710000', 'text': '710000 Arkitekter og rådgivende ingeniører'},
    {'id': 'VMB', 'text': 'MB Forskning og udvikling'},
    {'id': 'V72001', 'text': '72001 Forskning og udvikling, markedsmæssig'},
    {'id': 'V720001', 'text': '720001 Forskning og udvikling, markedsmæssig'},
    {'id': 'V72002',
     'text': '72002 Forskning og udvikling, ikke-markedsmæssig'},
    {'id': 'V720002',
     'text': '720002 Forskning og udvikling, ikke-markedsmæssig'},
    {'id': 'VMC', 'text': 'MC Reklame og øvrige erhvervsservice'},
    {'id': 'V73000', 'text': '73000 Reklame- og analysebureauer'},
    {'id': 'V730000', 'text': '730000 Reklame- og analysebureauer'},
    {'id': 'V74750', 'text': '74750 Dyrlæger og anden videnservice'},
    {'id': 'V740000', 'text': '740000 Anden videnservice'},
    {'id': 'V750000', 'text': '750000 Dyrlæger'},
    {'id': 'VN',
     'text': 'N Rejsebureauer, rengøring og anden operationel service'},
    {'id': 'V77000', 'text': '77000 Udlejning og leasing af materiel'},
    {'id': 'V770000', 'text': '770000 Udlejning og leasing af materiel'},
    {'id': 'V78000', 'text': '78000 Arbejdsformidling og vikarbureauer'},
    {'id': 'V780000', 'text': '780000 Arbejdsformidling og vikarbureauer'},
    {'id': 'V79000', 'text': '79000 Rejsebureauer'},
    {'id': 'V790000', 'text': '790000 Rejsebureauer'},
    {'id': 'V80820', 'text': '80820 Rengøring og anden operationel service'},
    {'id': 'V800000', 'text': '800000 Vagt og sikkerhedstjeneste'},
    {'id': 'V810000',
     'text': '810000 Ejendomsservice, rengøring og anlægsgartnere'},
    {'id': 'V820000', 'text': '820000 Anden operationel service'},
    {'id': 'VO_Q',
     'text': 'O_Q Offentlig administration, undervisning og sundhed'},
    {'id': 'VO', 'text': 'O Offentlig administration, forsvar og politi'},
    {'id': 'V84202', 'text': '84202 Offentlig administration mv.'},
    {'id': 'V840010', 'text': '840010 Offentlig administration'},
    {'id': 'V840022',
     'text': '840022 Forsvar, politi og retsvæsen mv., ikke-markedsmæssig'},
    {'id': 'V84101', 'text': '84101 Redningskorps mv., markedsmæssig'},
    {'id': 'V840021', 'text': '840021 Redningskorps mv., markedsmæssig'},
    {'id': 'VP', 'text': 'P Undervisning'},
    {'id': 'V85202', 'text': '85202 Undervisning, ikke-markedsmæssig'},
    {'id': 'V850010', 'text': '850010 Grundskoler'},
    {'id': 'V850020', 'text': '850020 Gymnasier og erhvervsfaglige skoler'},
    {'id': 'V850030', 'text': '850030 Videregående uddannelsesinstitutioner'},
    {'id': 'V850042',
     'text': '850042 Voksenundervisning mv., ikke-markedsmæssig'},
    {'id': 'V85101', 'text': '85101 Voksenundervisning mv., markedsmæssig'},
    {'id': 'V850041', 'text': '850041 Voksenundervisning mv., markedsmæssig'},
    {'id': 'VQ', 'text': 'Q Sundhed og socialvæsen'},
    {'id': 'VQA', 'text': 'QA Sundhedsvæsen'},
    {'id': 'V86000', 'text': '86000 Sundhedsvæsen'},
    {'id': 'V860010', 'text': '860010 Hospitaler'},
    {'id': 'V860020', 'text': '860020 Læger, tandlæger mv.'},
    {'id': 'VQB', 'text': 'QB Sociale institutioner'},
    {'id': 'V87880', 'text': '87880 Sociale institutioner'},
    {'id': 'V870000', 'text': '870000 Plejehjem mv.'},
    {'id': 'V880000', 'text': '880000 Daginstitutioner og dagcentre mv.'},
    {'id': 'VR_S', 'text': 'R_S Kultur, fritid og anden service'},
    {'id': 'VR', 'text': 'R Kultur og fritid'},
    {'id': 'V90920', 'text': '90920 Kunst, kultur og spil'},
    {'id': 'V900000', 'text': '900000 Teater, musik og kunst'},
    {'id': 'V910001', 'text': '910001 Biblioteker, museer mv., markedsmæssig'},
    {'id': 'V910002',
     'text': '910002 Biblioteker, museer mv., ikke-markedsmæssig'},
    {'id': 'V920000', 'text': '920000 Lotteri og andet spil'},
    {'id': 'V93000',
     'text': '93000 Sport, forlystelsesparker og andre fritidsaktiviteter'},
    {'id': 'V930011', 'text': '930011 Sport, markedsmæssig'},
    {'id': 'V930012', 'text': '930012 Sport, ikke-markedsmæssig'},
    {'id': 'V930020',
     'text': '930020 Forlystelsesparker og andre fritidsaktiviteter'},
    {'id': 'VSA', 'text': 'SA Andre serviceydelser'},
    {'id': 'V94000', 'text': '94000 Organisationer og foreninger'},
    {'id': 'V940000', 'text': '940000 Organisationer og foreninger'},
    {'id': 'V95000', 'text': '95000 Reparation af husholdningsudstyr'},
    {'id': 'V950000', 'text': '950000 Reparation af husholdningsudstyr'},
    {'id': 'V96000',
     'text': '96000 Frisører, vaskerier og andre serviceydelser'},
    {'id': 'V960000',
     'text': '960000 Frisører, vaskerier og andre serviceydelser'},
    {'id': 'VSB', 'text': 'SB Private husholdninger med ansat medhjælp'},
    {'id': 'V97000', 'text': '97000 Private husholdninger med ansat medhjælp'},
    {'id': 'V970000',
     'text': '970000 Private husholdninger med ansat medhjælp'}]},
  {'id': 'Tid',
   'text': 'tid',
   'elimination': False,
   'time': True,
   'values': [{'id': '1966', 'text': '1966'},
    {'id': '1967', 'text': '1967'},
    {'id': '1968', 'text': '1968'},
    {'id': '1969', 'text': '1969'},
    {'id': '1970', 'text': '1970'},
    {'id': '1971', 'text': '1971'},
    {'id': '1972', 'text': '1972'},
    {'id': '1973', 'text': '1973'},
    {'id': '1974', 'text': '1974'},
    {'id': '1975', 'text': '1975'},
    {'id': '1976', 'text': '1976'},
    {'id': '1977', 'text': '1977'},
    {'id': '1978', 'text': '1978'},
    {'id': '1979', 'text': '1979'},
    {'id': '1980', 'text': '1980'},
    {'id': '1981', 'text': '1981'},
    {'id': '1982', 'text': '1982'},
    {'id': '1983', 'text': '1983'},
    {'id': '1984', 'text': '1984'},
    {'id': '1985', 'text': '1985'},
    {'id': '1986', 'text': '1986'},
    {'id': '1987', 'text': '1987'},
    {'id': '1988', 'text': '1988'},
    {'id': '1989', 'text': '1989'},
    {'id': '1990', 'text': '1990'},
    {'id': '1991', 'text': '1991'},
    {'id': '1992', 'text': '1992'},
    {'id': '1993', 'text': '1993'},
    {'id': '1994', 'text': '1994'},
    {'id': '1995', 'text': '1995'},
    {'id': '1996', 'text': '1996'},
    {'id': '1997', 'text': '1997'},
    {'id': '1998', 'text': '1998'},
    {'id': '1999', 'text': '1999'},
    {'id': '2000', 'text': '2000'},
    {'id': '2001', 'text': '2001'},
    {'id': '2002', 'text': '2002'},
    {'id': '2003', 'text': '2003'},
    {'id': '2004', 'text': '2004'},
    {'id': '2005', 'text': '2005'},
    {'id': '2006', 'text': '2006'},
    {'id': '2007', 'text': '2007'},
    {'id': '2008', 'text': '2008'},
    {'id': '2009', 'text': '2009'},
    {'id': '2010', 'text': '2010'},
    {'id': '2011', 'text': '2011'},
    {'id': '2012', 'text': '2012'},
    {'id': '2013', 'text': '2013'},
    {'id': '2014', 'text': '2014'},
    {'id': '2015', 'text': '2015'},
    {'id': '2016', 'text': '2016'},
    {'id': '2017', 'text': '2017'},
    {'id': '2018', 'text': '2018'},
    {'id': '2019', 'text': '2019'},
    {'id': '2020', 'text': '2020'},
    {'id': '2021', 'text': '2021'},
    {'id': '2022', 'text': '2022'}]}]}

In [3]:
# Initialize the class with the target table
Lon_landbrug = DstApi('NAIO5')

# Get the table summary
Lon_landbrug.tablesummary(language='da')

Table NAIO5: Beskæftigelse og timer efter socioøkonomisk status, branche og tid
Last update: 2025-06-30T08:00:00

,variable name,# values,First value,First value label,Last value,Last value label,Time variable
0,SOCIO,9,EMPH_DC,Samlede præsterede timer (1000 timer),SELFEM_DC,Selvstændige ekskl. orlov mv. (antal),False
1,BRANCHE,234,V,I alt,V970000,970000 Private husholdninger med ansat medhjælp,False
2,Tid,57,1966,1966,2022,2022,True

In [4]:
levels = Lon_landbrug.variable_levels('SOCIO', language='da')
print(levels.to_string(index=False))

       id                                               text
  EMPH_DC              Samlede præsterede timer (1000 timer)
  SALH_DC     Præsterede timer for lønmodtagere (1000 timer)
 SELFH_DC     Præsterede timer for selvstændige (1000 timer)
  EMPM_DC                  Samlet antal beskæftigede (antal)
  SALM_DC                               Lønmodtagere (antal)
 SELFM_DC                               Selvstændige (antal)
 EMPEM_DC Samlet antal beskæftigede ekskl. orlov mv. (antal)
 SALEM_DC              Lønmodtagere ekskl. orlov mv. (antal)
SELFEM_DC              Selvstændige ekskl. orlov mv. (antal)

In [5]:
params = {
    'table': 'NAIO5',
    'format': 'BULK',
    'variables': [
        {'code': 'SOCIO', 'values': [
    "EMPH_DC", "SALH_DC"
]},
        {'code': 'BRANCHE', 'values': [
    "V01000",  # 010000 Landbrug og gartneri-(Anvendelse)
    "V020000",  # 020000 Skovbrug-(Anvendelse)
    "V030000",  # 030000 Fiskeri-(Anvendelse)
    "VB",       # B Råstofindvinding-(Anvendelse)
    "V10120",  # 10120 Føde-, drikke- og tobaksvareindustri-(Anvendelse)
    "VCB",      # CB Tekstil- og læderindustri-(Anvendelse)
    "VCC",      # CC Træ- og papirindustri, trykkerier-(Anvendelse)
    "VCD",      # CD Olieraffinaderier mv.-(Anvendelse)
    "VCE",      # CE Kemisk industri-(Anvendelse)
    "VCF",      # CF Medicinalindustri-(Anvendelse)
    "VCG",      # CG Plast-, glas- og betonindustri-(Anvendelse)
    "VCH",      # CH Metalindustri-(Anvendelse)
    "VCI",      # CI Elektronikindustri-(Anvendelse)
    "VCJ",      # CJ Fremst. af elektrisk udstyr-(Anvendelse)
    "VCK",      # CK Maskinindustri-(Anvendelse)
    "VCL",      # CL Transportmiddelindustri-(Anvendelse)
    "VCM",      # CM Møbel- og anden industri mv.-(Anvendelse)
    "VD_E",     # D_E Forsyningsvirksomhed-(Anvendelse)
    "VF",       # F Bygge og anlæg-(Anvendelse)
    "VG_I",     # G_I Handel og transport mv.-(Anvendelse)
    "VJ",       # J Information og kommunikation-(Anvendelse)
    "VK",       # K Finansiering og forsikring-(Anvendelse)
    "VLA",      # LA Ejendomshandel og udlejning af erhvervsejendomme-(Anvendelse)
    "VLB",      # LB Boliger-(Anvendelse)
    "VM_N",     # M_N Erhvervsservice-(Anvendelse)
    "VO_Q",     # O_Q Offentlig administration, undervisning og sundhed-(Anvendelse)
    "VR_S",     # R_S Kultur, fritid og anden service-(Anvendelse)
]
},
        {'code': 'TID', 'values': ['*']}
    ]
}
r = requests.post('https://api.statbank.dk/v1' + '/data', json=params)
print(r.text[:200])

SOCIO;BRANCHE;TID;INDHOLD
Samlede præsterede timer (1000 timer);B Råstofindvinding;2010;8009
Samlede præsterede timer (1000 timer);CB Tekstil- og læderindustri;2010;8863
Samlede præsterede timer (1

In [6]:
df = pd.read_csv(
    StringIO(
        requests.post('https://api.statbank.dk/v1' + '/data', json=params).text
    ), sep=';'
)

# Behandler og summer over data

## Tilgang

In [7]:
# 1) Sørg for at INDHOLD er tal (DK-format: komma som decimal)
df["INDHOLD"] = (
    df["INDHOLD"].astype(str)
      .str.replace("\u00a0", "", regex=False)  # non-breaking space
      .str.replace(" ", "", regex=False)       # mellemrum som tusindtals-sep
      .str.replace(".", "", regex=False)       # punktum som tusindtals-sep (hvis findes)
      .str.replace(",", ".", regex=False)      # komma -> punktum (decimal)
)
df["INDHOLD"] = pd.to_numeric(df["INDHOLD"], errors="coerce")

## Anvendelse

### Alt andet

In [8]:
# Brancher der skal trækkes fra (1-4)
exclude_codes = [
    "01000 Landbrug og gartneri",
    "10120 Føde-, drikke- og tobaksvareindustri"
]

# Dit nye id/navn for "resten"
new_name = "REST_ANVENDELSE"  # unikt id
new_id   = "REST_ANVENDELSE Øvrige brancher"

# Gruppér på alle andre dimensioner end TILGANG2 og INDHOLD
group_cols = [c for c in df.columns if c not in ["BRANCHE", "INDHOLD"]]

# Sum over alle brancher i tilgang, men udelad de fem ovenfor
new_rows = (
    df.loc[~df["BRANCHE"].isin(exclude_codes)]
      .groupby(group_cols, as_index=False)["INDHOLD"]
      .sum()
)

# Sæt den nye kode og tilføj tilbage
new_rows["BRANCHE"] = new_id
df = pd.concat([df, new_rows[df.columns]], ignore_index=True)

In [9]:
print("Antal REST-rækker:", (df["BRANCHE"] == new_id).sum())
print(df.loc[df["BRANCHE"] == new_id, ["SOCIO","TID","INDHOLD"]].head(200).to_string(index=False))

Antal REST-rækker: 114
                                         SOCIO  TID  INDHOLD
Præsterede timer for lønmodtagere (1000 timer) 1966  3252823
Præsterede timer for lønmodtagere (1000 timer) 1967  3240894
Præsterede timer for lønmodtagere (1000 timer) 1968  3224061
Præsterede timer for lønmodtagere (1000 timer) 1969  3253404
Præsterede timer for lønmodtagere (1000 timer) 1970  3285570
Præsterede timer for lønmodtagere (1000 timer) 1971  3244537
Præsterede timer for lønmodtagere (1000 timer) 1972  3216743
Præsterede timer for lønmodtagere (1000 timer) 1973  3188066
Præsterede timer for lønmodtagere (1000 timer) 1974  3143553
Præsterede timer for lønmodtagere (1000 timer) 1975  2966336
Præsterede timer for lønmodtagere (1000 timer) 1976  3060639
Præsterede timer for lønmodtagere (1000 timer) 1977  3009663
Præsterede timer for lønmodtagere (1000 timer) 1978  3009244
Præsterede timer for lønmodtagere (1000 timer) 1979  3060333
Præsterede timer for lønmodtagere (1000 timer) 1980  3109698
Præsterede timer for lønmodtagere (1000 timer) 1981  3007170
Præsterede timer for lønmodtagere (1000 timer) 1982  3057740
Præsterede timer for lønmodtagere (1000 timer) 1983  3062547
Præsterede timer for lønmodtagere (1000 timer) 1984  3121269
Præsterede timer for lønmodtagere (1000 timer) 1985  3193562
Præsterede timer for lønmodtagere (1000 timer) 1986  3302241
Præsterede timer for lønmodtagere (1000 timer) 1987  3255530
Præsterede timer for lønmodtagere (1000 timer) 1988  3207148
Præsterede timer for lønmodtagere (1000 timer) 1989  3177131
Præsterede timer for lønmodtagere (1000 timer) 1990  3157977
Præsterede timer for lønmodtagere (1000 timer) 1991  3118225
Præsterede timer for lønmodtagere (1000 timer) 1992  3123216
Præsterede timer for lønmodtagere (1000 timer) 1993  3069039
Præsterede timer for lønmodtagere (1000 timer) 1994  3062014
Præsterede timer for lønmodtagere (1000 timer) 1995  3118508
Præsterede timer for lønmodtagere (1000 timer) 1996  3138490
Præsterede timer for lønmodtagere (1000 timer) 1997  3249508
Præsterede timer for lønmodtagere (1000 timer) 1998  3336476
Præsterede timer for lønmodtagere (1000 timer) 1999  3416487
Præsterede timer for lønmodtagere (1000 timer) 2000  3455037
Præsterede timer for lønmodtagere (1000 timer) 2001  3512409
Præsterede timer for lønmodtagere (1000 timer) 2002  3481510
Præsterede timer for lønmodtagere (1000 timer) 2003  3445870
Præsterede timer for lønmodtagere (1000 timer) 2004  3446965
Præsterede timer for lønmodtagere (1000 timer) 2005  3507232
Præsterede timer for lønmodtagere (1000 timer) 2006  3616039
Præsterede timer for lønmodtagere (1000 timer) 2007  3668077
Præsterede timer for lønmodtagere (1000 timer) 2008  3727449
Præsterede timer for lønmodtagere (1000 timer) 2009  3583698
Præsterede timer for lønmodtagere (1000 timer) 2010  3516965
Præsterede timer for lønmodtagere (1000 timer) 2011  3551927
Præsterede timer for lønmodtagere (1000 timer) 2012  3500782
Præsterede timer for lønmodtagere (1000 timer) 2013  3512285
Præsterede timer for lønmodtagere (1000 timer) 2014  3508732
Præsterede timer for lønmodtagere (1000 timer) 2015  3533325
Præsterede timer for lønmodtagere (1000 timer) 2016  3628619
Præsterede timer for lønmodtagere (1000 timer) 2017  3667296
Præsterede timer for lønmodtagere (1000 timer) 2018  3672593
Præsterede timer for lønmodtagere (1000 timer) 2019  3728601
Præsterede timer for lønmodtagere (1000 timer) 2020  3594582
Præsterede timer for lønmodtagere (1000 timer) 2021  3801068
Præsterede timer for lønmodtagere (1000 timer) 2022  3960298
         Samlede præsterede timer (1000 timer) 1966  3742182
         Samlede præsterede timer (1000 timer) 1967  3720867
         Samlede præsterede timer (1000 timer) 1968  3695254
         Samlede præsterede timer (1000 timer) 1969  3716009
         Samlede præsterede timer (1000 timer) 1970  3741101
         Samlede præsterede timer (1000 timer) 1971  3694889
         Samlede præsterede timer (1000 timer) 1972  3653882
         Samlede præsterede timer (1000 timer) 1973  3614336
         Samlede præsterede timer (1000 timer) 1974  3566698
         Samlede præsterede timer (1000 timer) 1975  3379346
         Samlede præsterede timer (1000 timer) 1976  3472797
         Samlede præsterede timer (1000 timer) 1977  3418194
         Samlede præsterede timer (1000 timer) 1978  3410781
         Samlede præsterede timer (1000 timer) 1979  3444395
         Samlede præsterede timer (1000 timer) 1980  3477283
         Samlede præsterede timer (1000 timer) 1981  3356998
         Samlede præsterede timer (1000 timer) 1982  3400968
         Samlede præsterede timer (1000 timer) 1983  3394252
         Samlede præsterede timer (1000 timer) 1984  3445565
         Samlede præsterede timer (1000 timer) 1985  3514700
         Samlede præsterede timer (1000 timer) 1986  3625889
         Samlede præsterede timer (1000 timer) 1987  3568130
         Samlede præsterede timer (1000 timer) 1988  3517672
         Samlede præsterede timer (1000 timer) 1989  3475337
         Samlede præsterede timer (1000 timer) 1990  3434810
         Samlede præsterede timer (1000 timer) 1991  3395609
         Samlede præsterede timer (1000 timer) 1992  3413744
         Samlede præsterede timer (1000 timer) 1993  3357281
         Samlede præsterede timer (1000 timer) 1994  3342697
         Samlede præsterede timer (1000 timer) 1995  3401971
         Samlede præsterede timer (1000 timer) 1996  3431762
         Samlede præsterede timer (1000 timer) 1997  3539072
         Samlede præsterede timer (1000 timer) 1998  3632582
         Samlede præsterede timer (1000 timer) 1999  3714509
         Samlede præsterede timer (1000 timer) 2000  3772557
         Samlede præsterede timer (1000 timer) 2001  3824171
         Samlede præsterede timer (1000 timer) 2002  3809762
         Samlede præsterede timer (1000 timer) 2003  3776588
         Samlede præsterede timer (1000 timer) 2004  3761275
         Samlede præsterede timer (1000 timer) 2005  3814540
         Samlede præsterede timer (1000 timer) 2006  3929729
         Samlede præsterede timer (1000 timer) 2007  3967488
         Samlede præsterede timer (1000 timer) 2008  4018058
         Samlede præsterede timer (1000 timer) 2009  3861885
         Samlede præsterede timer (1000 timer) 2010  3790107
         Samlede præsterede timer (1000 timer) 2011  3830075
         Samlede præsterede timer (1000 timer) 2012  3769454
         Samlede præsterede timer (1000 timer) 2013  3781533
         Samlede præsterede timer (1000 timer) 2014  3776795
         Samlede præsterede timer (1000 timer) 2015  3815080
         Samlede præsterede timer (1000 timer) 2016  3899913
         Samlede præsterede timer (1000 timer) 2017  3935591
         Samlede præsterede timer (1000 timer) 2018  3934302
         Samlede præsterede timer (1000 timer) 2019  3972380
         Samlede præsterede timer (1000 timer) 2020  3827066
         Samlede præsterede timer (1000 timer) 2021  4062261
         Samlede præsterede timer (1000 timer) 2022  4225398

In [10]:
excodes = [
    "O_Q Offentlig administration, undervisning og sundhed"
]

include_codes = [
    "010000 Landbrug og gartneri",
    "100010 Slagterier",
    "100030 Mejerier",
    "100040x100050 Anden fødevareindustri (100040, 100050)",
    "REST_ANVENDELSE Øvrige brancher"
]

group_cols = [c for c in df.columns if c not in ["BRANCHE", "INDHOLD"]]

# Sum af de valgte brancher
total = (
    df.loc[df["BRANCHE"].isin(include_codes)]
      .groupby(group_cols, as_index=False)["INDHOLD"]
      .sum()
)

# Sum af det offentlige
offentlig = (
    df.loc[df["BRANCHE"].isin(excodes)]
      .groupby(group_cols, as_index=False)["INDHOLD"]
      .sum()
)

# Privat = Total minus offentlig
privat = total.merge(offentlig, on=group_cols, suffixes=("_total", "_off"))
privat["INDHOLD"] = privat["INDHOLD_total"] - privat["INDHOLD_off"]
privat = privat[group_cols + ["INDHOLD"]]
privat["BRANCHE"] = "Privat"

df = pd.concat([df, privat], ignore_index=True)
offentlig

                                              SOCIO   TID  INDHOLD
0    Præsterede timer for lønmodtagere (1000 timer)  1966   584670
1    Præsterede timer for lønmodtagere (1000 timer)  1967   629046
2    Præsterede timer for lønmodtagere (1000 timer)  1968   640500
3    Præsterede timer for lønmodtagere (1000 timer)  1969   676771
4    Præsterede timer for lønmodtagere (1000 timer)  1970   712595
..                                              ...   ...      ...
109           Samlede præsterede timer (1000 timer)  2018  1211743
110           Samlede præsterede timer (1000 timer)  2019  1221900
111           Samlede præsterede timer (1000 timer)  2020  1206371
112           Samlede præsterede timer (1000 timer)  2021  1272731
113           Samlede præsterede timer (1000 timer)  2022  1280027

[114 rows x 3 columns]

# Gem udvalgt data

In [11]:
# 1. Vælg de kategorier du vil beholde
udvalgte_anvendelse = [
    "01000 Landbrug og gartneri",
    "10120 Føde-, drikke- og tobaksvareindustri",
    "REST_ANVENDELSE Øvrige brancher",
]

# 2. Lav det nye datasæt ved at filtrere
# Vi tjekker om TILGANG2 er i vores liste OG om ANVENDELSE er i vores liste
df_subset = df[(df["BRANCHE"].isin(udvalgte_anvendelse))
].copy()

# 3. Tjek resultatet
print(f"Det nye datasæt har {df_subset.shape[0]} rækker.")
display(df_subset.head())
df_subset.to_csv('Data69/Lontimer_landbrugsdata.csv', index=False)

Det nye datasæt har 342 rækker.

,SOCIO,BRANCHE,TID,INDHOLD
23,Samlede præsterede timer (1000 timer),01000 Landbrug og gartneri,2010,98594
26,Samlede præsterede timer (1000 timer),"10120 Føde-, drikke- og tobaksvareindustri",2010,79289
50,Præsterede timer for lønmodtagere (1000 timer),01000 Landbrug og gartneri,2010,50879
53,Præsterede timer for lønmodtagere (1000 timer),"10120 Føde-, drikke- og tobaksvareindustri",2010,77950
77,Samlede præsterede timer (1000 timer),01000 Landbrug og gartneri,1972,463150