In [52]:
# Start by importing necessary packages
import requests
import pandas as pd
import numpy as np
from IPython.display import display
from io import StringIO

from dstapi import DstApi # The helper class

In [53]:
# Directly embed parameters in the URL with response.get()
requests.get('https://api.statbank.dk/v1' + '/tableinfo' + "?id=metrox1&format=JSON").json()

# Pass a dictionary of parameters to requests.get()
params = {'id': 'TILSKUD', 'format': 'JSON'}
requests.get('https://api.statbank.dk/v1' + '/tableinfo', params=params).json()

# Use response.post() - note the change in the name of the parameter about the table's name
# I'm also adding here a language parameter - most tables are available in both Danish and English
params = {'table': 'TILSKUD', 'format': 'JSON', 'lang':'da'}
requests.post('https://api.statbank.dk/v1' + '/tableinfo', json=params).json()

{'id': 'TILSKUD',
 'text': 'Direkte tilskud til landbrugssektoren',
 'description': 'Direkte tilskud til landbrugssektoren efter type og tid',
 'unit': 'Mio. kr.',
 'suppressedDataValue': '0',
 'updated': '2018-10-08T08:00:00',
 'active': False,
 'contacts': [{'name': 'Simone Thun',
   'phone': '+4551369251',
   'mail': 'sit@dst.dk'}],
 'documentation': {'id': '97613485-5c2d-45d4-bdba-8ddccbbf77ec',
  'url': 'https://www.dst.dk/statistikdokumentation/97613485-5c2d-45d4-bdba-8ddccbbf77ec'},
 'footnote': None,
 'variables': [{'id': 'TYPE',
   'text': 'type',
   'elimination': False,
   'time': False,
   'values': [{'id': '000', 'text': 'DRIFTSTILSKUD I ALT'},
    {'id': '005', 'text': 'PRODUKTTILKNYTTEDE TILSKUD I ALT'},
    {'id': '010', 'text': 'Hektarstøtte i alt'},
    {'id': '015', 'text': 'Præmie til proteinafgrøder'},
    {'id': '020', 'text': 'Tilskud til energiafgrøder'},
    {'id': '025', 'text': 'Støtte til produktion af korn'},
    {'id': '030', 'text': 'Støtte til produktion af oliefrø og oliehør'},
    {'id': '035', 'text': 'Støtte til produktion af bælgsæd'},
    {'id': '040', 'text': 'Animalsk støtte i alt'},
    {'id': '045', 'text': 'Præmier til ammekøer'},
    {'id': '050', 'text': 'Præmier til moderfår'},
    {'id': '055', 'text': 'Handyrspræmie'},
    {'id': '060', 'text': 'Slagtepræmie'},
    {'id': '065', 'text': 'National konvolut vedr. husdyr'},
    {'id': '070', 'text': 'Mælkepræmie'},
    {'id': '075', 'text': 'Kvotesuspensionsordning for mælk'},
    {'id': '080', 'text': 'GENERELLE TILSKUD I ALT'},
    {'id': '085', 'text': 'Enkeltbetalingsordning, arealtilskud'},
    {'id': '090', 'text': 'Braklægningsstøtte'},
    {'id': '095', 'text': 'Ekstensiveringspræmie'},
    {'id': '100', 'text': 'Rentetilskud/forbedringsordning'},
    {'id': '105', 'text': 'Økologiske arealtilskud'},
    {'id': '110', 'text': 'Tilskud til læplantning'},
    {'id': '115', 'text': 'Miljøvenlige foranstaltninger'},
    {'id': '120', 'text': 'Andre generelle tilskud'},
    {'id': '125', 'text': 'ENGANGS- OG INVESTERINGSTILSKUD I ALT'},
    {'id': '130', 'text': 'Ydelsestilskud til yngre landbrugere'},
    {'id': '135', 'text': 'Erstatning ved nedslagtning af dyr'},
    {'id': '140', 'text': 'Statslige afdragsbidrag, jordbrugslån'},
    {'id': '145', 'text': 'Miljøforbedrende investeringer'},
    {'id': '150', 'text': 'Præmie for ophør af mælkeproduktion'},
    {'id': '155', 'text': 'Støtte til braklægning (5 årig)'}]},
  {'id': 'Tid',
   'text': 'tid',
   'elimination': False,
   'time': True,
   'values': [{'id': '1990', 'text': '1990'},
    {'id': '1991', 'text': '1991'},
    {'id': '1992', 'text': '1992'},
    {'id': '1993', 'text': '1993'},
    {'id': '1994', 'text': '1994'},
    {'id': '1995', 'text': '1995'},
    {'id': '1996', 'text': '1996'},
    {'id': '1997', 'text': '1997'},
    {'id': '1998', 'text': '1998'},
    {'id': '1999', 'text': '1999'},
    {'id': '2000', 'text': '2000'},
    {'id': '2001', 'text': '2001'},
    {'id': '2002', 'text': '2002'},
    {'id': '2003', 'text': '2003'},
    {'id': '2004', 'text': '2004'},
    {'id': '2005', 'text': '2005'},
    {'id': '2006', 'text': '2006'},
    {'id': '2007', 'text': '2007'},
    {'id': '2008', 'text': '2008'},
    {'id': '2009', 'text': '2009'},
    {'id': '2010', 'text': '2010'},
    {'id': '2011', 'text': '2011'},
    {'id': '2012', 'text': '2012'},
    {'id': '2013', 'text': '2013'},
    {'id': '2014', 'text': '2014'},
    {'id': '2015', 'text': '2015'},
    {'id': '2016', 'text': '2016'},
    {'id': '2017', 'text': '2017'}]}]}

In [54]:
# Directly embed parameters in the URL with response.get()
requests.get('https://api.statbank.dk/v1' + '/tableinfo' + "?id=metrox1&format=JSON").json()

# Pass a dictionary of parameters to requests.get()
params = {'id': 'TILSKUD1', 'format': 'JSON'}
requests.get('https://api.statbank.dk/v1' + '/tableinfo', params=params).json()

# Use response.post() - note the change in the name of the parameter about the table's name
# I'm also adding here a language parameter - most tables are available in both Danish and English
params = {'table': 'TILSKUD1', 'format': 'JSON', 'lang':'da'}
requests.post('https://api.statbank.dk/v1' + '/tableinfo', json=params).json()

{'id': 'TILSKUD1',
 'text': 'Direkte tilskud til landbrugssektoren',
 'description': 'Direkte tilskud til landbrugssektoren efter tilskudsart og tid',
 'unit': 'Mio. kr.',
 'suppressedDataValue': '0',
 'updated': '2023-05-24T08:00:00',
 'active': False,
 'contacts': [{'name': 'Simone Thun',
   'phone': '+4551369251',
   'mail': 'sit@dst.dk'}],
 'documentation': {'id': '97613485-5c2d-45d4-bdba-8ddccbbf77ec',
  'url': 'https://www.dst.dk/statistikdokumentation/97613485-5c2d-45d4-bdba-8ddccbbf77ec'},
 'footnote': {'text': 'Beløbene i tabellen angiver det år, hvor tilskuddene er udbetalt, ikke nødvendigvis det år som udbetalingerne henfører til. 2021: Minkerstatningerne indgår ikke i tabellen. Fra 2020 er tilskudsarten Pleje af græs og naturarealer blevet udspecificeret under Miljøtilskud. Tilskud, som hørte under Målrettede efterafgrøder, er fra 2020 rykket under Målrettet kvælstofregulering, da tilskudsarten ikke længere er national. De seneste to år er foreløbige.',
  'mandatory': False},
 'variables': [{'id': 'TILSKUDSART',
   'text': 'tilskudsart',
   'elimination': False,
   'time': False,
   'values': [{'id': '160', 'text': '1 TILSKUD I ALT'},
    {'id': '165', 'text': '2 DIREKTE STØTTE I ALT'},
    {'id': '170', 'text': '2.1 Grundbetaling'},
    {'id': '175', 'text': '2.2 Grønne krav'},
    {'id': '180', 'text': '2.3 Unge landbrugere'},
    {'id': '185', 'text': '2.4 Ø-støtte'},
    {'id': '190', 'text': '2.5 Slagtepræmie'},
    {'id': '195', 'text': '3 LANDDISTRIKTSMIDLER I ALT'},
    {'id': '200', 'text': '3.1 Miljøtilskud'},
    {'id': '205', 'text': '3.1.1 Økologisk arealtilskud'},
    {'id': '206', 'text': '3.1.2 Pleje af græs og naturarealer (2020 -)'},
    {'id': '208', 'text': '3.1.3 Målrettet kvælstofregulering (2020 -)'},
    {'id': '210', 'text': '3.2 Investeringstilskud'},
    {'id': '215', 'text': '3.3 Øvrige tilskud fra landdistriktsmidlerne'},
    {'id': '220', 'text': '4 NATIONALE TILSKUDSORDNINGER I ALT'},
    {'id': '225', 'text': '4.1 Målrettede efterafgrøder'},
    {'id': '230', 'text': '4.2 Øvrige nationale tilskudsordninger'},
    {'id': '235', 'text': '5 ENGANGSTILSKUD I ALT'},
    {'id': '240', 'text': '5.1 Mælkepræmie'}]},
  {'id': 'Tid',
   'text': 'tid',
   'elimination': False,
   'time': True,
   'values': [{'id': '2015', 'text': '2015'},
    {'id': '2016', 'text': '2016'},
    {'id': '2017', 'text': '2017'},
    {'id': '2018', 'text': '2018'},
    {'id': '2019', 'text': '2019'},
    {'id': '2020', 'text': '2020'},
    {'id': '2021', 'text': '2021'},
    {'id': '2022', 'text': '2022'}]}]}

In [55]:
# Initialize the class with the target table
TILSKUD = DstApi('TILSKUD')

# Get the table summary
TILSKUD.tablesummary(language='da')

Table TILSKUD: Direkte tilskud til landbrugssektoren efter type og tid
Last update: 2018-10-08T08:00:00

,variable name,# values,First value,First value label,Last value,Last value label,Time variable
0,TYPE,32,000,DRIFTSTILSKUD I ALT,155,Støtte til braklægning (5 årig),False
1,Tid,28,1990,1990,2017,2017,True

In [56]:
# Initialize the class with the target table
TILSKUD1 = DstApi('TILSKUD1')

# Get the table summary
TILSKUD1.tablesummary(language='da')

Table TILSKUD1: Direkte tilskud til landbrugssektoren efter tilskudsart og tid
Last update: 2023-05-24T08:00:00

,variable name,# values,First value,First value label,Last value,Last value label,Time variable
0,TILSKUDSART,19,160,1 TILSKUD I ALT,240,5.1 Mælkepræmie,False
1,Tid,8,2015,2015,2022,2022,True

In [57]:
levels = TILSKUD.variable_levels('TYPE', language='da')
print(levels.to_string(index=False))

 id                                        text
000                         DRIFTSTILSKUD I ALT
005            PRODUKTTILKNYTTEDE TILSKUD I ALT
010                          Hektarstøtte i alt
015                  Præmie til proteinafgrøder
020                  Tilskud til energiafgrøder
025               Støtte til produktion af korn
030 Støtte til produktion af oliefrø og oliehør
035            Støtte til produktion af bælgsæd
040                       Animalsk støtte i alt
045                        Præmier til ammekøer
050                        Præmier til moderfår
055                               Handyrspræmie
060                                Slagtepræmie
065              National konvolut vedr. husdyr
070                                 Mælkepræmie
075            Kvotesuspensionsordning for mælk
080                     GENERELLE TILSKUD I ALT
085        Enkeltbetalingsordning, arealtilskud
090                          Braklægningsstøtte
095                       Ekstensiveringspræmie
100             Rentetilskud/forbedringsordning
105                     Økologiske arealtilskud
110                     Tilskud til læplantning
115               Miljøvenlige foranstaltninger
120                     Andre generelle tilskud
125       ENGANGS- OG INVESTERINGSTILSKUD I ALT
130        Ydelsestilskud til yngre landbrugere
135          Erstatning ved nedslagtning af dyr
140       Statslige afdragsbidrag, jordbrugslån
145              Miljøforbedrende investeringer
150         Præmie for ophør af mælkeproduktion
155             Støtte til braklægning (5 årig)

In [58]:
levels = TILSKUD1.variable_levels('TILSKUDSART', language='da')
print(levels.to_string(index=False))

 id                                         text
160                              1 TILSKUD I ALT
165                       2 DIREKTE STØTTE I ALT
170                            2.1 Grundbetaling
175                              2.2 Grønne krav
180                         2.3 Unge landbrugere
185                                 2.4 Ø-støtte
190                             2.5 Slagtepræmie
195                  3 LANDDISTRIKTSMIDLER I ALT
200                             3.1 Miljøtilskud
205                 3.1.1 Økologisk arealtilskud
206 3.1.2 Pleje af græs og naturarealer (2020 -)
208  3.1.3 Målrettet kvælstofregulering (2020 -)
210                      3.2 Investeringstilskud
215 3.3 Øvrige tilskud fra landdistriktsmidlerne
220          4 NATIONALE TILSKUDSORDNINGER I ALT
225                 4.1 Målrettede efterafgrøder
230       4.2 Øvrige nationale tilskudsordninger
235                       5 ENGANGSTILSKUD I ALT
240                              5.1 Mælkepræmie

In [59]:
params = {
    'table': 'TILSKUD',
    'format': 'BULK',
    'variables': [
        {'code': 'TYPE', 'values': ['010','085','090', '095']},
        {'code': 'TID', 'values': ['*']}
    ]
}
r = requests.post('https://api.statbank.dk/v1' + '/data', json=params)
print(r.text[:200])

df_f2015 = pd.read_csv(
    StringIO(
        requests.post('https://api.statbank.dk/v1' + '/data', json=params).text
    ), sep=';'
)
print(df_f2015.columns.tolist())
print(df_f2015.head())

TYPE;TID;INDHOLD
Hektarstøtte i alt;1990;..
Enkeltbetalingsordning, arealtilskud;1990;..
Braklægningsstøtte;1990;..
Ekstensiveringspræmie;1990;..
Hektarstøtte i alt;1991;..
Enkeltbetalingsordnin
['TYPE', 'TID', 'INDHOLD']
                                   TYPE   TID INDHOLD
0                    Hektarstøtte i alt  1990      ..
1  Enkeltbetalingsordning, arealtilskud  1990      ..
2                    Braklægningsstøtte  1990      ..
3                 Ekstensiveringspræmie  1990      ..
4                    Hektarstøtte i alt  1991      ..

In [60]:
params1 = {
    'table': 'TILSKUD1',
    'format': 'BULK',
    'variables': [
        {'code': 'TILSKUDSART', 'values': ['170','175']},
        {'code': 'TID', 'values': ['*']}
    ]
}
r = requests.post('https://api.statbank.dk/v1' + '/data', json=params1)
print(r.text[:200])

df_2015 = pd.read_csv(
    StringIO(
        requests.post('https://api.statbank.dk/v1' + '/data', json=params1).text
    ), sep=';'
)
print(df_2015.columns.tolist())
print(df_2015.head())

TILSKUDSART;TID;INDHOLD
2.1 Grundbetaling;2015;4023
2.2 Grønne krav;2015;1863
2.1 Grundbetaling;2016;4055
2.2 Grønne krav;2016;1838
2.1 Grundbetaling;2017;3774
2.2 Grønne krav;2017;1727
2.1 Gru
['TILSKUDSART', 'TID', 'INDHOLD']
         TILSKUDSART   TID  INDHOLD
0  2.1 Grundbetaling  2015     4023
1    2.2 Grønne krav  2015     1863
2  2.1 Grundbetaling  2016     4055
3    2.2 Grønne krav  2016     1838
4  2.1 Grundbetaling  2017     3774

In [61]:
# 1) Sørg for at INDHOLD er tal (DK-format: komma som decimal)
df_f2015["INDHOLD"] = (
    df_f2015["INDHOLD"].astype(str)
      .str.replace("\u00a0", "", regex=False)  # non-breaking space
      .str.replace(" ", "", regex=False)       # mellemrum som tusindtals-sep
      .str.replace(".", "", regex=False)       # punktum som tusindtals-sep (hvis findes)
      .str.replace(",", ".", regex=False)      # komma -> punktum (decimal)
)
df_f2015["INDHOLD"] = pd.to_numeric(df_f2015["INDHOLD"], errors="coerce")
df_2015["INDHOLD"] = (
    df_2015["INDHOLD"].astype(str)
      .str.replace("\u00a0", "", regex=False)  # non-breaking space
      .str.replace(" ", "", regex=False)       # mellemrum som tusindtals-sep
      .str.replace(".", "", regex=False)       # punktum som tusindtals-sep (hvis findes)
      .str.replace(",", ".", regex=False)      # komma -> punktum (decimal)
)
df_2015["INDHOLD"] = pd.to_numeric(df_2015["INDHOLD"], errors="coerce")

In [ ]:
#Trækker braklægning og græs fra
df_f2005_hek = df_f2015[df_f2015['TYPE'] == 'Hektarstøtte i alt'].copy().fillna(0)
df_f2005_hek.drop(columns=['TYPE'], inplace=True)
df_f2005_brak = df_f2015[df_f2015['TYPE'] == 'Braklægningsstøtte'].copy().fillna(0)
df_f2005_brak.drop(columns=['TYPE'], inplace=True)
df_f2005_ekst = df_f2015[df_f2015['TYPE'] == 'Ekstensiveringspræmie'].copy().fillna(0)
df_f2005_ekst.drop(columns=['TYPE'], inplace=True)
df_2005_2015 = df_f2015[df_f2015['TYPE'] == 'Enkeltbetalingsordning, arealtilskud'].copy().fillna(0)
df_2005_2015.drop(columns=['TYPE'], inplace=True)
df_2015_grundbetaling = df_2015[df_2015['TILSKUDSART'] == '2.1 Grundbetaling'].copy().fillna(0)
df_2015_grundbetaling.drop(columns=['TILSKUDSART'], inplace=True)
df_2015_gron = df_2015[df_2015['TILSKUDSART'] == '2.2 Grønne krav'].copy().fillna(0)
df_2015_gron.drop(columns=['TILSKUDSART'], inplace=True)

df_f2005_hek = df_f2005_hek.set_index(['TID'])
df_f2005_brak = df_f2005_brak.set_index(['TID'])
df_f2005_ekst = df_f2005_ekst.set_index(['TID'])
df_2005_2015 = df_2005_2015.set_index(['TID'])
df_2015_grundbetaling = df_2015_grundbetaling.set_index(['TID'])
df_2015_gron = df_2015_gron.set_index(['TID'])  

df_f2005 = df_f2005_hek['INDHOLD'] + df_f2005_brak['INDHOLD'] + df_f2005_ekst['INDHOLD']
df_f2005 = df_f2005.reset_index(name='INDHOLD')
df_f2005 = df_f2005[df_f2005['TID'] < 2005].copy()
df_2005_2015 = df_2005_2015['INDHOLD'].reset_index(name='INDHOLD')
df_2005_2015 = df_2005_2015[(df_2005_2015['TID'] >= 2005) & (df_2005_2015['TID'] < 2015)].copy()
df_e2015 = df_2015_grundbetaling['INDHOLD'] + df_2015_gron['INDHOLD']
df_e2015 = df_e2015.reset_index(name='INDHOLD')
df_e2015 = df_e2015[df_e2015['TID'] >= 2015].copy()
df_f2005
df_2005_2015
df_e2015

df_tilskud_samlet = pd.concat([df_f2005, df_2005_2015, df_e2015], ignore_index=True)

# Sorter efter TID for at få dem i kronologisk rækkefølge
df_tilskud_samlet = df_tilskud_samlet.sort_values('TID').reset_index(drop=True)
df_tilskud_samlet
df_tilskud_samlet.to_csv('Data69/landbrugsdata_tilskud.csv', index=False)

     TID  INDHOLD
0   1990      0.0
1   1991      0.0
2   1992    754.0
3   1993   2848.0
4   1994   4133.0
5   1995   4854.0
6   1996   4700.0
7   1997   4686.0
8   1998   4726.0
9   1999   4614.0
10  2000   4660.0
11  2001   5044.0
12  2002   4992.0
13  2003   5006.0
14  2004   5046.0
15  2005   6583.0
16  2006   6981.0
17  2007   6895.0
18  2008   7273.0
19  2009   7105.0
20  2010   6779.0
21  2011   6562.0
22  2012   6866.0
23  2013   6945.0
24  2014   6363.0
25  2015   5886.0
26  2016   5893.0
27  2017   5501.0
28  2018   6344.0
29  2019   5568.0
30  2020   5740.0
31  2021   5405.0
32  2022   5404.0