In [1]:
# Start by importing necessary packages
import requests
import pandas as pd
import numpy as np
from IPython.display import display
from io import StringIO

from dstapi import DstApi # The helper class

In [2]:
# Directly embed parameters in the URL with response.get()
requests.get('https://api.statbank.dk/v1' + '/tableinfo' + "?id=metrox1&format=JSON").json()

# Pass a dictionary of parameters to requests.get()
params = {'id': 'NABK69', 'format': 'JSON'}
requests.get('https://api.statbank.dk/v1' + '/tableinfo', params=params).json()

# Use response.post() - note the change in the name of the parameter about the table's name
# I'm also adding here a language parameter - most tables are available in both Danish and English
params = {'table': 'NABK69', 'format': 'JSON', 'lang':'da'}
requests.post('https://api.statbank.dk/v1' + '/tableinfo', json=params).json()

{'id': 'NABK69',
 'text': 'Akkumulations- og statuskonti, investering og beholdning af faste aktiver (69-gruppering)',
 'description': 'Akkumulations- og statuskonti, investering og beholdning af faste aktiver (69-gruppering) efter beholdning / strøm, aktiv, branche, prisenhed og tid',
 'unit': 'Mio. kr.',
 'suppressedDataValue': '0',
 'updated': '2025-07-04T08:00:00',
 'active': True,
 'contacts': [{'name': 'Bo Siemsen',
   'phone': '+4521579724',
   'mail': 'bsm@dst.dk'}],
 'documentation': {'id': 'caf4e327-d063-497a-94da-1997828c77f8',
  'url': 'https://www.dst.dk/statistikdokumentation/caf4e327-d063-497a-94da-1997828c77f8'},
 'footnote': None,
 'variables': [{'id': 'BEHOLD',
   'text': 'beholdning / strøm',
   'elimination': False,
   'time': False,
   'values': [{'id': 'LSN',
     'text': 'AN.11 Faste aktiver, nettobeholdning, primo året'},
    {'id': 'LSG', 'text': 'Faste aktiver, bruttobeholdning, primo året'},
    {'id': 'P51G', 'text': 'P.51g Faste bruttoinvesteringer'},
    {'id': 'P51C', 'text': 'P.51c Forbrug af fast realkapital'},
    {'id': 'K3', 'text': 'K.3 Tab ved katastrofer'},
    {'id': 'K7', 'text': 'K.7 Nominelle kapitalgevinster og -tab'},
    {'id': 'K72', 'text': 'heraf K.7.2 Reale kapitalgevinster og -tab'},
    {'id': 'LEN', 'text': 'AN.11 Faste aktiver, nettobeholdning ultimo året'},
    {'id': 'LEG', 'text': 'Faste aktiver, bruttobeholdning, ultimo året'}]},
  {'id': 'AKTIV',
   'text': 'aktiv',
   'elimination': False,
   'time': False,
   'values': [{'id': 'N11', 'text': 'Faste aktiver'},
    {'id': 'N111', 'text': 'Boliger'},
    {'id': 'N1121', 'text': 'Andre bygninger'},
    {'id': 'N1122_3', 'text': 'Anlæg'},
    {'id': 'N1131', 'text': 'Transportmidler'},
    {'id': 'N11P',
     'text': 'ICT udstyr, andre maskiner og inventar samt våbensystemer'},
    {'id': 'N115', 'text': 'Stambesætninger mv.'},
    {'id': 'N117', 'text': 'Intellektuelle rettigheder'}]},
  {'id': 'BRANCHE',
   'text': 'branche',
   'elimination': False,
   'time': False,
   'values': [{'id': 'V', 'text': 'I alt'},
    {'id': 'VMEMO', 'text': 'Heraf: Offentlig forvaltning og service'},
    {'id': 'V01000', 'text': '01000 Landbrug og gartneri'},
    {'id': 'V02000', 'text': '02000 Skovbrug'},
    {'id': 'V03000', 'text': '03000 Fiskeri'},
    {'id': 'V06090', 'text': '06090 Råstofindvinding'},
    {'id': 'V10120', 'text': '10120 Føde-, drikke- og tobaksvareindustri'},
    {'id': 'V13150', 'text': '13150 Tekstil- og læderindustri'},
    {'id': 'V16000', 'text': '16000 Træindustri'},
    {'id': 'V17000', 'text': '17000 Papirindustri'},
    {'id': 'V18000', 'text': '18000 Trykkerier mv.'},
    {'id': 'V19000', 'text': '19000 Olieraffinaderier mv.'},
    {'id': 'V20000', 'text': '20000 Kemisk industri'},
    {'id': 'V21000', 'text': '21000 Medicinalindustri'},
    {'id': 'V22000', 'text': '22000 Plast- og gummiindustri'},
    {'id': 'V23000', 'text': '23000 Glas- og betonindustri'},
    {'id': 'V24000', 'text': '24000 Fremst. af metal'},
    {'id': 'V25000', 'text': '25000 Metalvareindustri'},
    {'id': 'V26000', 'text': '26000 Elektronikindustri'},
    {'id': 'V27000', 'text': '27000 Fremst. af elektrisk udstyr'},
    {'id': 'V28000', 'text': '28000 Maskinindustri'},
    {'id': 'V29000', 'text': '29000 Fremst. af motorkøretøjer og dele hertil'},
    {'id': 'V30000',
     'text': '30000 Fremst. af skibe og andre transportmidler'},
    {'id': 'V31320', 'text': '31320 Møbel- og anden industri'},
    {'id': 'V33000',
     'text': '33000 Reparation og installation af maskiner og udstyr'},
    {'id': 'V35000', 'text': '35000 Energiforsyning'},
    {'id': 'V36000', 'text': '36000 Vandforsyning'},
    {'id': 'V37390', 'text': '37390 Renovation, affaldsbehandling mv.'},
    {'id': 'V41430', 'text': '41430 Bygge og anlæg'},
    {'id': 'V45000', 'text': '45000 Bilhandel og -værksteder mv.'},
    {'id': 'V46000', 'text': '46000 Engroshandel'},
    {'id': 'V47000', 'text': '47000 Detailhandel'},
    {'id': 'V49000', 'text': '49000 Landtransport'},
    {'id': 'V50000', 'text': '50000 Skibsfart'},
    {'id': 'V51000', 'text': '51000 Luftfart'},
    {'id': 'V52000', 'text': '52000 Hjælpevirksomhed til transport'},
    {'id': 'V53000', 'text': '53000 Post og kurertjeneste'},
    {'id': 'V55560', 'text': '55560 Hoteller og restauranter'},
    {'id': 'V58000', 'text': '58000 Udgivervirksomhed'},
    {'id': 'V59600',
     'text': '59600 Radio- og tv-stationer samt produktion af film, tv, mus'},
    {'id': 'V61000', 'text': '61000 Telekommunikation'},
    {'id': 'V62630', 'text': '62630 It- og informationstjenester'},
    {'id': 'V64000', 'text': '64000 Finansiel virksomhed'},
    {'id': 'V65000', 'text': '65000 Forsikring og pension'},
    {'id': 'V66000', 'text': '66000 Finansiel service'},
    {'id': 'V68100', 'text': '68100 Ejendomsmæglere mv.'},
    {'id': 'V68300', 'text': '68300 Udlejning af erhvervsejendomme'},
    {'id': 'V68203', 'text': '68203 Boliger, husleje i lejeboliger'},
    {'id': 'V68204', 'text': '68204 Boliger, ejerboliger mv.'},
    {'id': 'V69700',
     'text': '69700 Advokater, revisorer og virksomhedskonsulenter'},
    {'id': 'V71000', 'text': '71000 Arkitekter og rådgivende ingeniører'},
    {'id': 'V72001', 'text': '72001 Forskning og udvikling, markedsmæssig'},
    {'id': 'V72002',
     'text': '72002 Forskning og udvikling, ikke-markedsmæssig'},
    {'id': 'V73000', 'text': '73000 Reklame- og analysebureauer'},
    {'id': 'V74750', 'text': '74750 Dyrlæger og anden videnservice'},
    {'id': 'V77000', 'text': '77000 Udlejning og leasing af materiel'},
    {'id': 'V78000', 'text': '78000 Arbejdsformidling og vikarbureauer'},
    {'id': 'V79000', 'text': '79000 Rejsebureauer'},
    {'id': 'V80820', 'text': '80820 Rengøring og anden operationel service'},
    {'id': 'V84202', 'text': '84202 Offentlig administration mv.'},
    {'id': 'V84101', 'text': '84101 Redningskorps mv., markedsmæssig'},
    {'id': 'V85202', 'text': '85202 Undervisning, ikke-markedsmæssig'},
    {'id': 'V85101', 'text': '85101 Voksenundervisning mv., markedsmæssig'},
    {'id': 'V86000', 'text': '86000 Sundhedsvæsen'},
    {'id': 'V87880', 'text': '87880 Sociale institutioner'},
    {'id': 'V90920', 'text': '90920 Kunst, kultur og spil'},
    {'id': 'V93000',
     'text': '93000 Sport, forlystelsesparker og andre fritidsaktiviteter'},
    {'id': 'V94000', 'text': '94000 Organisationer og foreninger'},
    {'id': 'V95000', 'text': '95000 Reparation af husholdningsudstyr'},
    {'id': 'V96000',
     'text': '96000 Frisører, vaskerier og andre serviceydelser'},
    {'id': 'V97000',
     'text': '97000 Private husholdninger med ansat medhjælp'}]},
  {'id': 'PRISENHED',
   'text': 'prisenhed',
   'elimination': False,
   'time': False,
   'values': [{'id': 'V', 'text': 'Løbende priser'},
    {'id': 'LAN', 'text': '2020-priser, kædede værdier'}]},
  {'id': 'Tid',
   'text': 'tid',
   'elimination': False,
   'time': True,
   'values': [{'id': '1966', 'text': '1966'},
    {'id': '1967', 'text': '1967'},
    {'id': '1968', 'text': '1968'},
    {'id': '1969', 'text': '1969'},
    {'id': '1970', 'text': '1970'},
    {'id': '1971', 'text': '1971'},
    {'id': '1972', 'text': '1972'},
    {'id': '1973', 'text': '1973'},
    {'id': '1974', 'text': '1974'},
    {'id': '1975', 'text': '1975'},
    {'id': '1976', 'text': '1976'},
    {'id': '1977', 'text': '1977'},
    {'id': '1978', 'text': '1978'},
    {'id': '1979', 'text': '1979'},
    {'id': '1980', 'text': '1980'},
    {'id': '1981', 'text': '1981'},
    {'id': '1982', 'text': '1982'},
    {'id': '1983', 'text': '1983'},
    {'id': '1984', 'text': '1984'},
    {'id': '1985', 'text': '1985'},
    {'id': '1986', 'text': '1986'},
    {'id': '1987', 'text': '1987'},
    {'id': '1988', 'text': '1988'},
    {'id': '1989', 'text': '1989'},
    {'id': '1990', 'text': '1990'},
    {'id': '1991', 'text': '1991'},
    {'id': '1992', 'text': '1992'},
    {'id': '1993', 'text': '1993'},
    {'id': '1994', 'text': '1994'},
    {'id': '1995', 'text': '1995'},
    {'id': '1996', 'text': '1996'},
    {'id': '1997', 'text': '1997'},
    {'id': '1998', 'text': '1998'},
    {'id': '1999', 'text': '1999'},
    {'id': '2000', 'text': '2000'},
    {'id': '2001', 'text': '2001'},
    {'id': '2002', 'text': '2002'},
    {'id': '2003', 'text': '2003'},
    {'id': '2004', 'text': '2004'},
    {'id': '2005', 'text': '2005'},
    {'id': '2006', 'text': '2006'},
    {'id': '2007', 'text': '2007'},
    {'id': '2008', 'text': '2008'},
    {'id': '2009', 'text': '2009'},
    {'id': '2010', 'text': '2010'},
    {'id': '2011', 'text': '2011'},
    {'id': '2012', 'text': '2012'},
    {'id': '2013', 'text': '2013'},
    {'id': '2014', 'text': '2014'},
    {'id': '2015', 'text': '2015'},
    {'id': '2016', 'text': '2016'},
    {'id': '2017', 'text': '2017'},
    {'id': '2018', 'text': '2018'},
    {'id': '2019', 'text': '2019'},
    {'id': '2020', 'text': '2020'},
    {'id': '2021', 'text': '2021'},
    {'id': '2022', 'text': '2022'},
    {'id': '2023', 'text': '2023'},
    {'id': '2024', 'text': '2024'}]}]}

In [3]:
# Initialize the class with the target table
Kapital_landbrug = DstApi('NABK69')

# Get the table summary
Kapital_landbrug.tablesummary(language='da')

Table NABK69: Akkumulations- og statuskonti, investering og beholdning af faste aktiver (69-gruppering) efter beholdning / strøm, aktiv, branche, prisenhed og tid
Last update: 2025-07-04T08:00:00

,variable name,# values,First value,First value label,Last value,Last value label,Time variable
0,BEHOLD,9,LSN,"AN.11 Faste aktiver, nettobeholdning, primo året",LEG,"Faste aktiver, bruttobeholdning, ultimo året",False
1,AKTIV,8,N11,Faste aktiver,N117,Intellektuelle rettigheder,False
2,BRANCHE,71,V,I alt,V97000,97000 Private husholdninger med ansat medhjælp,False
3,PRISENHED,2,V,Løbende priser,LAN,"2020-priser, kædede værdier",False
4,Tid,59,1966,1966,2024,2024,True

In [4]:
levels = Kapital_landbrug.variable_levels('BEHOLD', language='da')
print(levels.to_string(index=False))

  id                                             text
 LSN AN.11 Faste aktiver, nettobeholdning, primo året
 LSG      Faste aktiver, bruttobeholdning, primo året
P51G                  P.51g Faste bruttoinvesteringer
P51C                P.51c Forbrug af fast realkapital
  K3                          K.3 Tab ved katastrofer
  K7           K.7 Nominelle kapitalgevinster og -tab
 K72       heraf K.7.2 Reale kapitalgevinster og -tab
 LEN AN.11 Faste aktiver, nettobeholdning ultimo året
 LEG     Faste aktiver, bruttobeholdning, ultimo året

In [5]:
levels = Kapital_landbrug.variable_levels('BRANCHE', language='da')
print(levels.to_string(index=False))

    id                                                          text
     V                                                         I alt
 VMEMO                       Heraf: Offentlig forvaltning og service
V01000                                    01000 Landbrug og gartneri
V02000                                                02000 Skovbrug
V03000                                                 03000 Fiskeri
V06090                                        06090 Råstofindvinding
V10120                    10120 Føde-, drikke- og tobaksvareindustri
V13150                               13150 Tekstil- og læderindustri
V16000                                             16000 Træindustri
V17000                                           17000 Papirindustri
V18000                                          18000 Trykkerier mv.
V19000                                   19000 Olieraffinaderier mv.
V20000                                         20000 Kemisk industri
V21000                                       21000 Medicinalindustri
V22000                                 22000 Plast- og gummiindustri
V23000                                  23000 Glas- og betonindustri
V24000                                        24000 Fremst. af metal
V25000                                       25000 Metalvareindustri
V26000                                      26000 Elektronikindustri
V27000                             27000 Fremst. af elektrisk udstyr
V28000                                          28000 Maskinindustri
V29000                29000 Fremst. af motorkøretøjer og dele hertil
V30000               30000 Fremst. af skibe og andre transportmidler
V31320                                31320 Møbel- og anden industri
V33000        33000 Reparation og installation af maskiner og udstyr
V35000                                         35000 Energiforsyning
V36000                                           36000 Vandforsyning
V37390                       37390 Renovation, affaldsbehandling mv.
V41430                                          41430 Bygge og anlæg
V45000                            45000 Bilhandel og -værksteder mv.
V46000                                            46000 Engroshandel
V47000                                            47000 Detailhandel
V49000                                           49000 Landtransport
V50000                                               50000 Skibsfart
V51000                                                51000 Luftfart
V52000                          52000 Hjælpevirksomhed til transport
V53000                                   53000 Post og kurertjeneste
V55560                                55560 Hoteller og restauranter
V58000                                       58000 Udgivervirksomhed
V59600 59600 Radio- og tv-stationer samt produktion af film, tv, mus
V61000                                       61000 Telekommunikation
V62630                            62630 It- og informationstjenester
V64000                                    64000 Finansiel virksomhed
V65000                                   65000 Forsikring og pension
V66000                                       66000 Finansiel service
V68100                                     68100 Ejendomsmæglere mv.
V68300                          68300 Udlejning af erhvervsejendomme
V68203                          68203 Boliger, husleje i lejeboliger
V68204                                68204 Boliger, ejerboliger mv.
V69700          69700 Advokater, revisorer og virksomhedskonsulenter
V71000                     71000 Arkitekter og rådgivende ingeniører
V72001                   72001 Forskning og udvikling, markedsmæssig
V72002              72002 Forskning og udvikling, ikke-markedsmæssig
V73000                             73000 Reklame- og analysebureauer
V74750                          74750 Dyrlæger og anden videnservice
V77000                        77000 Udlejning og leasing af materiel
V78000                      78000 Arbejdsformidling og vikarbureauer
V79000                                           79000 Rejsebureauer
V80820                  80820 Rengøring og anden operationel service
V84202                            84202 Offentlig administration mv.
V84101                        84101 Redningskorps mv., markedsmæssig
V85202                        85202 Undervisning, ikke-markedsmæssig
V85101                   85101 Voksenundervisning mv., markedsmæssig
V86000                                           86000 Sundhedsvæsen
V87880                                   87880 Sociale institutioner
V90920                                   90920 Kunst, kultur og spil
V93000   93000 Sport, forlystelsesparker og andre fritidsaktiviteter
V94000                            94000 Organisationer og foreninger
V95000                        95000 Reparation af husholdningsudstyr
V96000             96000 Frisører, vaskerier og andre serviceydelser
V97000                97000 Private husholdninger med ansat medhjælp

In [6]:
params = {
    'table': 'NABK69',
    'format': 'BULK',
    'variables': [
        {'code': 'BEHOLD', 'values': [
    "LEN", "P51G"
]},
        {'code': 'AKTIV', 'values': [
    "N11"
]},
        {'code': 'BRANCHE', 'values': ['*']},

        {'code': 'PRISENHED', 'values': ['*']},
        {'code': 'TID', 'values': ['*']}
    ]
}
r = requests.post('https://api.statbank.dk/v1' + '/data', json=params)
print(r.text[:200])

BEHOLD;AKTIV;BRANCHE;PRISENHED;TID;INDHOLD
AN.11 Faste aktiver, nettobeholdning ultimo året;Faste aktiver;I alt;2020-priser, kædede værdier;1966;2817411
AN.11 Faste aktiver, nettobeholdning ultimo å

In [7]:
df = pd.read_csv(
    StringIO(
        requests.post('https://api.statbank.dk/v1' + '/data', json=params).text
    ), sep=';'
)

# Filtrer både på ID og tekst
df = df.loc[
    ~df['BRANCHE'].isin(['V', 'VMEMO']) & 
    ~df['BRANCHE'].str.contains('Heraf: Offentlig forvaltning og service', na=False) & 
    ~df['BRANCHE'].str.contains('I alt', na=False)
]

In [8]:
# 1) Sørg for at INDHOLD er tal (DK-format: komma som decimal)
df["INDHOLD"] = (
    df["INDHOLD"].astype(str)
      .str.replace("\u00a0", "", regex=False)  # non-breaking space
      .str.replace(" ", "", regex=False)       # mellemrum som tusindtals-sep
      .str.replace(".", "", regex=False)       # punktum som tusindtals-sep (hvis findes)
      .str.replace(",", ".", regex=False)      # komma -> punktum (decimal)
)
df["INDHOLD"] = pd.to_numeric(df["INDHOLD"], errors="coerce")

In [9]:
df.drop(columns=['AKTIV'],inplace=True)
# df.to_csv('Data/Kapital_landbrugsdata.csv', index=False)
df

,BEHOLD,BRANCHE,PRISENHED,TID,INDHOLD
2,"AN.11 Faste aktiver, nettobeholdning ultimo året",01000 Landbrug og gartneri,"2020-priser, kædede værdier",1966,222779.0
3,"AN.11 Faste aktiver, nettobeholdning ultimo året",01000 Landbrug og gartneri,Løbende priser,1966,25165.0
4,"AN.11 Faste aktiver, nettobeholdning ultimo året",02000 Skovbrug,"2020-priser, kædede værdier",1966,1720.0
5,"AN.11 Faste aktiver, nettobeholdning ultimo året",02000 Skovbrug,Løbende priser,1966,181.0
6,"AN.11 Faste aktiver, nettobeholdning ultimo året",03000 Fiskeri,"2020-priser, kædede værdier",1966,4293.0
...,...,...,...,...,...
16469,"AN.11 Faste aktiver, nettobeholdning ultimo året",95000 Reparation af husholdningsudstyr,Løbende priser,2024,1746.0
16470,"AN.11 Faste aktiver, nettobeholdning ultimo året","96000 Frisører, vaskerier og andre serviceydelser","2020-priser, kædede værdier",2024,6912.0
16471,"AN.11 Faste aktiver, nettobeholdning ultimo året","96000 Frisører, vaskerier og andre serviceydelser",Løbende priser,2024,7795.0
16472,"AN.11 Faste aktiver, nettobeholdning ultimo året",97000 Private husholdninger med ansat medhjælp,"2020-priser, kædede værdier",2024,0.0
16473,"AN.11 Faste aktiver, nettobeholdning ultimo året",97000 Private husholdninger med ansat medhjælp,Løbende priser,2024,0.0

### Omregn så det kan lægges sammen

In [10]:
df_landbrug_for = df.loc[df['PRISENHED'] != 'Løbende priser']
df_landbrug_for.drop(columns=['PRISENHED'], inplace=True)
df_landbrug_loebende = df.loc[df['PRISENHED'] == 'Løbende priser']
df_landbrug_loebende.drop(columns=['PRISENHED'], inplace=True)
df_landbrug_loebende=df_landbrug_loebende.loc[df_landbrug_loebende['TID']!=1966]

# Sæt index for alignment
df_landbrug_for_indexed = df_landbrug_for.set_index(['BEHOLD', 'BRANCHE', 'TID'])
df_landbrug_loebende_indexed = df_landbrug_loebende.set_index(['BEHOLD', 'BRANCHE', 'TID'])

# Beregn mængdeindeks
df_landbrug_for_q = df_landbrug_for_indexed.groupby(['BEHOLD','BRANCHE'])['INDHOLD'].shift(1)
Maengdeindeks = df_landbrug_for_indexed['INDHOLD'] / df_landbrug_for_q

# Multiplicer
df_landbrug_lobende_q = df_landbrug_loebende_indexed.groupby(['BEHOLD','BRANCHE'])['INDHOLD'].shift(1)
Forige_aar_priser = df_landbrug_lobende_q * Maengdeindeks

# Håndter NaN
Forige_aar_priser = Forige_aar_priser.fillna(0)  # eller .dropna()

# Reset index for at få kolonner tilbage
Forige_aar_priser = Forige_aar_priser.reset_index(name='INDHOLD')

# Tilføj PRISENHED kolonne med værdien "Forige års priser" (eller hvad du vil kalde den)
Forige_aar_priser['PRISENHED'] = 'Forige års priser'  # eller 'Foregående års priser'

# Sørg for at kolonnerne matcher df's kolonner
# Hvis df har andre kolonner, skal de også være med
Forige_aar_priser = Forige_aar_priser[df.columns]

# Tilføj tilbage til df
df = pd.concat([df, Forige_aar_priser], ignore_index=True)
df

C:\Users\b431385\AppData\Local\Temp\ipykernel_3512\284791575.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_landbrug_for.drop(columns=['PRISENHED'], inplace=True)
C:\Users\b431385\AppData\Local\Temp\ipykernel_3512\284791575.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_landbrug_loebende.drop(columns=['PRISENHED'], inplace=True)

,BEHOLD,BRANCHE,PRISENHED,TID,INDHOLD
0,"AN.11 Faste aktiver, nettobeholdning ultimo året",01000 Landbrug og gartneri,"2020-priser, kædede værdier",1966,222779.0
1,"AN.11 Faste aktiver, nettobeholdning ultimo året",01000 Landbrug og gartneri,Løbende priser,1966,25165.0
2,"AN.11 Faste aktiver, nettobeholdning ultimo året",02000 Skovbrug,"2020-priser, kædede værdier",1966,1720.0
3,"AN.11 Faste aktiver, nettobeholdning ultimo året",02000 Skovbrug,Løbende priser,1966,181.0
4,"AN.11 Faste aktiver, nettobeholdning ultimo året",03000 Fiskeri,"2020-priser, kædede værdier",1966,4293.0
...,...,...,...,...,...
24007,P.51g Faste bruttoinvesteringer,97000 Private husholdninger med ansat medhjælp,Forige års priser,2018,0.0
24008,P.51g Faste bruttoinvesteringer,97000 Private husholdninger med ansat medhjælp,Forige års priser,2019,0.0
24009,P.51g Faste bruttoinvesteringer,97000 Private husholdninger med ansat medhjælp,Forige års priser,2020,0.0
24010,P.51g Faste bruttoinvesteringer,97000 Private husholdninger med ansat medhjælp,Forige års priser,2021,0.0
24011,P.51g Faste bruttoinvesteringer,97000 Private husholdninger med ansat medhjælp,Forige års priser,2022,0.0

In [11]:
# Brancher der skal trækkes fra (1-4)
exclude_codes = [
    "01000 Landbrug og gartneri",
    "10120 Føde-, drikke- og tobaksvareindustri"
]

# Dit nye id/navn for "resten"
new_name = "REST_ANVENDELSE"  # unikt id
new_id   = "REST_ANVENDELSE Øvrige brancher"

# Gruppér på alle andre dimensioner end TILGANG2 og INDHOLD
group_cols = [c for c in df.columns if c not in ["BRANCHE", "INDHOLD"]]

# Sum over alle brancher i tilgang, men udelad de fem ovenfor
new_rows = (
    df.loc[~df["BRANCHE"].isin(exclude_codes)]
      .groupby(group_cols, as_index=False)["INDHOLD"]
      .sum()
)

# Sæt den nye kode og tilføj tilbage
new_rows["BRANCHE"] = new_id
df = pd.concat([df, new_rows[df.columns]], ignore_index=True)

In [12]:
print("Antal REST-rækker:", (df["BRANCHE"] == new_id).sum())
print(df.loc[df["BRANCHE"] == new_id, ["BEHOLD","PRISENHED","TID","INDHOLD"]].head(200).to_string(index=False))

Antal REST-rækker: 348
                                          BEHOLD                   PRISENHED  TID      INDHOLD
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1966 2.618163e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1967 2.738303e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1968 2.867006e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1969 3.015495e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1970 3.161059e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1971 3.302298e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1972 3.467494e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1973 3.631240e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1974 3.755637e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1975 3.856260e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1976 3.992820e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1977 4.114787e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1978 4.233512e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1979 4.350333e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1980 4.435830e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1981 4.471498e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1982 4.517509e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1983 4.564886e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1984 4.625448e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1985 4.710206e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1986 4.837386e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1987 4.962141e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1988 5.055391e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1989 5.137935e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1990 5.217291e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1991 5.264800e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1992 5.305384e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1993 5.328639e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1994 5.354683e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1995 5.403081e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1996 5.462484e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1997 5.531111e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1998 5.612542e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 1999 5.682056e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2000 5.773271e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2001 5.852073e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2002 5.918328e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2003 5.980902e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2004 6.046439e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2005 6.132550e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2006 6.270696e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2007 6.395005e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2008 6.486901e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2009 6.533631e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2010 6.550770e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2011 6.568622e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2012 6.599838e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2013 6.638025e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2014 6.696875e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2015 6.769376e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2016 6.870825e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2017 6.985059e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2018 7.107156e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2019 7.209258e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2020 7.324959e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2021 7.488001e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2022 7.648052e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2023 7.786450e+06
AN.11 Faste aktiver, nettobeholdning ultimo året 2020-priser, kædede værdier 2024 7.930718e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1966 0.000000e+00
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1967 0.000000e+00
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1968 2.727346e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1969 3.007271e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1970 3.404192e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1971 3.803807e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1972 4.238399e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1973 4.795849e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1974 5.602315e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1975 6.689737e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1976 7.514368e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1977 8.345561e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1978 9.373738e+05
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1979 1.039147e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1980 1.160915e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1981 1.318681e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1982 1.493454e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1983 1.645908e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1984 1.787210e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1985 1.904148e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1986 2.022172e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1987 2.095138e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1988 2.235016e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1989 2.401239e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1990 2.575462e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1991 2.693775e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1992 2.800831e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1993 2.889173e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1994 2.963843e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1995 3.054169e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1996 3.154722e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1997 3.318292e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1998 3.458740e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 1999 3.586606e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2000 3.772388e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2001 3.910365e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2002 4.101467e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2003 4.236912e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2004 4.383777e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2005 4.539382e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2006 4.769302e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2007 5.077506e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2008 5.367523e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2009 5.614527e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2010 5.315086e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2011 5.395247e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2012 5.580194e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2013 5.761077e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2014 5.887213e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2015 6.019268e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2016 6.150996e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2017 6.407109e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2018 6.632741e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2019 6.889144e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2020 7.161939e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2021 7.489113e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2022 7.864333e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2023 8.885496e+06
AN.11 Faste aktiver, nettobeholdning ultimo året           Forige års priser 2024 9.560719e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1966 2.472880e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1967 2.618890e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1968 2.874740e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1969 3.258970e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1970 3.654490e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1971 4.054780e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1972 4.589390e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1973 5.420710e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1974 6.525280e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1975 7.256860e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1976 8.091980e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1977 9.098970e+05
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1978 1.010356e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1979 1.137149e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1980 1.307595e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1981 1.476468e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1982 1.624854e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1983 1.758578e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1984 1.862693e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1985 1.958882e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1986 2.033779e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1987 2.188507e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1988 2.358039e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1989 2.529117e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1990 2.664031e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1991 2.776433e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1992 2.873969e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1993 2.946588e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1994 3.022521e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1995 3.115493e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1996 3.267169e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1997 3.398810e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1998 3.535917e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 1999 3.704390e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2000 3.851474e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2001 4.051481e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2002 4.188159e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2003 4.333194e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2004 4.471940e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2005 4.659326e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2006 4.974912e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2007 5.286041e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2008 5.572898e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2009 5.300844e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2010 5.380760e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2011 5.553602e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2012 5.727165e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2013 5.834002e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2014 5.953458e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2015 6.057686e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2016 6.300395e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2017 6.517097e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2018 6.790820e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2019 7.048386e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2020 7.326042e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2021 7.699949e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2022 8.729081e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2023 9.390873e+06
AN.11 Faste aktiver, nettobeholdning ultimo året              Løbende priser 2024 9.645696e+06
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1966 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1967 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1968 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1969 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1970 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1971 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1972 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1973 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1974 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1975 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1976 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1977 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1978 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1979 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1980 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1981 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1982 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1983 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1984 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1985 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1986 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1987 0.000000e+00
                 P.51g Faste bruttoinvesteringer 2020-priser, kædede værdier 1988 0.000000e+00

In [13]:
# 1. Vælg de kategorier du vil beholde
udvalgte_anvendelse = [
    "01000 Landbrug og gartneri",
    "10120 Føde-, drikke- og tobaksvareindustri",
    "REST_ANVENDELSE Øvrige brancher",
]

# 2. Lav det nye datasæt ved at filtrere
# Vi tjekker om TILGANG2 er i vores liste OG om ANVENDELSE er i vores liste
df_subset = df[(df["BRANCHE"].isin(udvalgte_anvendelse))
].copy()

# 3. Tjek resultatet
print(f"Det nye datasæt har {df_subset.shape[0]} rækker.")
display(df_subset.head())
df_subset.to_csv('Data69/Kapital_landbrugsdata.csv', index=False)

Det nye datasæt har 1044 rækker.

,BEHOLD,BRANCHE,PRISENHED,TID,INDHOLD
0,"AN.11 Faste aktiver, nettobeholdning ultimo året",01000 Landbrug og gartneri,"2020-priser, kædede værdier",1966,222779.0
1,"AN.11 Faste aktiver, nettobeholdning ultimo året",01000 Landbrug og gartneri,Løbende priser,1966,25165.0
8,"AN.11 Faste aktiver, nettobeholdning ultimo året","10120 Føde-, drikke- og tobaksvareindustri","2020-priser, kædede værdier",1966,34654.0
9,"AN.11 Faste aktiver, nettobeholdning ultimo året","10120 Føde-, drikke- og tobaksvareindustri",Løbende priser,1966,4388.0
138,P.51g Faste bruttoinvesteringer,01000 Landbrug og gartneri,"2020-priser, kædede værdier",1966,NaN