In [1]:
import pandas as pd
import numpy as np

# Indlæs filen
df_input = pd.read_csv('Data69/input_landbrugsdata.csv')
df_timer = pd.read_csv('Data69/Lontimer_landbrugsdata.csv')
#filter for løbende priser og foregående års priser
df_lonsum = df_input.loc[(df_input['TILGANG1'] == 'Aflønning af ansatte') & 
                         (df_input['PRISENHED'] == 'Løbende priser')]

#fjern prishenhed
df_lonsum.drop(columns=['PRISENHED'],inplace=True)
df_lonsum.drop(columns=['TILGANG1'],inplace=True)
df_timer.drop(columns=['SOCIO'],inplace=True)

mapping = {
    '01000 Landbrug og gartneri': '01000',
    '01000 Landbrug og gartneri- (Anvendelse)': '01000',
    '10120 Føde-, drikke- og tobaksvareindustri': '10120',
    '10120 Føde-, drikke- og tobaksvareindustri- (Anvendelse)': '10120',
    'REST_TILGANG Øvrige brancher': 'REST',
    'REST_ANVENDELSE Øvrige brancher': 'REST'
}

# Erstat navnene i de to kolonner
df_timer['BRANCHE'] = df_timer['BRANCHE'].replace(mapping)
df_lonsum['ANVENDELSE'] = df_lonsum['ANVENDELSE'].replace(mapping)

#set index
df_lonsum.set_index(['ANVENDELSE', 'TID'],inplace=True)
df_timer.set_index(['BRANCHE', 'TID'],inplace=True)


#tjek
df_lonsum

C:\Users\b431385\AppData\Local\Temp\ipykernel_32252\3156344830.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lonsum.drop(columns=['PRISENHED'],inplace=True)
C:\Users\b431385\AppData\Local\Temp\ipykernel_32252\3156344830.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lonsum.drop(columns=['TILGANG1'],inplace=True)
C:\Users\b431385\AppData\Local\Temp\ipykernel_32252\3156344830.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lonsum['ANVENDELSE'] = df_lonsum['ANVENDELSE'].replace(mapping)

                     INDHOLD
ANVENDELSE TID
01000      2002     5285.780
10120      2002    21264.214
01000      1998     4777.547
10120      1998    18823.890
01000      1980     2139.681
...                      ...
REST       2018  1124998.842
           2019  1163144.088
           2020  1178056.495
           2021  1245661.908
           2022  1333027.881

[171 rows x 1 columns]

In [2]:
# Sørg for at index-navnene er identiske, ellers kan Pandas brokke sig ved division
df_timer.index.names = ['ANVENDELSE', 'TID']
df_timer_output = df_timer.reset_index()
df_timer_output.columns = ['ANVENDELSE', 'TID', 'TIMER']
# 4. Gem til CSV
df_timer_output.to_csv('Data69/Timer_landbrugsdata.csv', index=False)
df_timer_output

    ANVENDELSE   TID    TIMER
0        01000  1966   630077
1        10120  1966   232125
2        01000  1967   595974
3        10120  1967   220326
4        01000  1968   561953
..         ...   ...      ...
166       REST  2018  3934302
167       REST  2019  3972380
168       REST  2020  3827066
169       REST  2021  4062261
170       REST  2022  4225398

[171 rows x 3 columns]

In [3]:
# 1. Udfør divisionen specifikt på 'INDHOLD' kolonnerne
df_timelon = df_lonsum['INDHOLD'] / (df_timer['INDHOLD'] / 1000)

# 2. Gør det til et DataFrame og giv kolonnen et sigende navn
df_timelon = df_timelon.to_frame(name='TIMELOEN_KR')

# 3. FLYT INDEX TIL KOLONNER (Dette er løsningen på dit problem!)
# Når du gør dette, bliver 'ANVENDELSE' og 'TID' til rigtige kolonner i din CSV
df_timelon_output = df_timelon.reset_index()

# 4. Gem til CSV
df_timelon_output.to_csv('Data69/TimeLon_landbrugsdata.csv', index=False)

# Vis resultatet for at tjekke
df_timelon_output

    ANVENDELSE   TID  TIMELOEN_KR
0        01000  1966     1.364024
1        01000  1967     1.459260
2        01000  1968     1.537552
3        01000  1969     1.635656
4        01000  1970     1.587802
..         ...   ...          ...
166       REST  2018   285.946234
167       REST  2019   292.807860
168       REST  2020   307.822362
169       REST  2021   306.642510
170       REST  2022   315.479839

[171 rows x 3 columns]